//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CounselQuickPlatinum.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt")]
        public global::System.Drawing.Font DefaultFont {
            get {
                return ((global::System.Drawing.Font)(this["DefaultFont"]));
            }
            set {
                this["DefaultFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ControlText")]
        public global::System.Drawing.Color DefaultForeColor {
            get {
                return ((global::System.Drawing.Color)(this["DefaultForeColor"]));
            }
            set {
                this["DefaultForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control")]
        public global::System.Drawing.Color DefaultBackColor {
            get {
                return ((global::System.Drawing.Color)(this["DefaultBackColor"]));
            }
            set {
                this["DefaultBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control")]
        public global::System.Drawing.Color ButtonColor {
            get {
                return ((global::System.Drawing.Color)(this["ButtonColor"]));
            }
            set {
                this["ButtonColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ControlText")]
        public global::System.Drawing.Color ButtonForeColor {
            get {
                return ((global::System.Drawing.Color)(this["ButtonForeColor"]));
            }
            set {
                this["ButtonForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt")]
        public global::System.Drawing.Font ButtonFont {
            get {
                return ((global::System.Drawing.Font)(this["ButtonFont"]));
            }
            set {
                this["ButtonFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Window")]
        public global::System.Drawing.Color DataGridViewBackColor {
            get {
                return ((global::System.Drawing.Color)(this["DataGridViewBackColor"]));
            }
            set {
                this["DataGridViewBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Single")]
        public global::System.Windows.Forms.DataGridViewCellBorderStyle DataGridViewCellBorderStyle {
            get {
                return ((global::System.Windows.Forms.DataGridViewCellBorderStyle)(this["DataGridViewCellBorderStyle"]));
            }
            set {
                this["DataGridViewCellBorderStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Form1Location {
            get {
                return ((global::System.Drawing.Point)(this["Form1Location"]));
            }
            set {
                this["Form1Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size Form1Size {
            get {
                return ((global::System.Drawing.Size)(this["Form1Size"]));
            }
            set {
                this["Form1Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string Form1SavedWindowState {
            get {
                return ((string)(this["Form1SavedWindowState"]));
            }
            set {
                this["Form1SavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Form1Height {
            get {
                return ((int)(this["Form1Height"]));
            }
            set {
                this["Form1Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Form1Width {
            get {
                return ((int)(this["Form1Width"]));
            }
            set {
                this["Form1Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point AboutLocation {
            get {
                return ((global::System.Drawing.Point)(this["AboutLocation"]));
            }
            set {
                this["AboutLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size AboutSize {
            get {
                return ((global::System.Drawing.Size)(this["AboutSize"]));
            }
            set {
                this["AboutSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string AboutSavedWindowState {
            get {
                return ((string)(this["AboutSavedWindowState"]));
            }
            set {
                this["AboutSavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AboutHeight {
            get {
                return ((int)(this["AboutHeight"]));
            }
            set {
                this["AboutHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AboutWidth {
            get {
                return ((int)(this["AboutWidth"]));
            }
            set {
                this["AboutWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Form2Location {
            get {
                return ((global::System.Drawing.Point)(this["Form2Location"]));
            }
            set {
                this["Form2Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size Form2Size {
            get {
                return ((global::System.Drawing.Size)(this["Form2Size"]));
            }
            set {
                this["Form2Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string Form2SavedWindowState {
            get {
                return ((string)(this["Form2SavedWindowState"]));
            }
            set {
                this["Form2SavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Form2Height {
            get {
                return ((int)(this["Form2Height"]));
            }
            set {
                this["Form2Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Form2Width {
            get {
                return ((int)(this["Form2Width"]));
            }
            set {
                this["Form2Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point AssessmentDialogLocation {
            get {
                return ((global::System.Drawing.Point)(this["AssessmentDialogLocation"]));
            }
            set {
                this["AssessmentDialogLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size AssessmentDialogSize {
            get {
                return ((global::System.Drawing.Size)(this["AssessmentDialogSize"]));
            }
            set {
                this["AssessmentDialogSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string AssessmentDialogSavedWindowState {
            get {
                return ((string)(this["AssessmentDialogSavedWindowState"]));
            }
            set {
                this["AssessmentDialogSavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AssessmentDialogHeight {
            get {
                return ((int)(this["AssessmentDialogHeight"]));
            }
            set {
                this["AssessmentDialogHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AssessmentDialogWidth {
            get {
                return ((int)(this["AssessmentDialogWidth"]));
            }
            set {
                this["AssessmentDialogWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point ConfirmDetachDocumentDialogLocation {
            get {
                return ((global::System.Drawing.Point)(this["ConfirmDetachDocumentDialogLocation"]));
            }
            set {
                this["ConfirmDetachDocumentDialogLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size ConfirmDetachDocumentDialogSize {
            get {
                return ((global::System.Drawing.Size)(this["ConfirmDetachDocumentDialogSize"]));
            }
            set {
                this["ConfirmDetachDocumentDialogSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string ConfirmDetachDocumentDialogSavedWindowState {
            get {
                return ((string)(this["ConfirmDetachDocumentDialogSavedWindowState"]));
            }
            set {
                this["ConfirmDetachDocumentDialogSavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long ConfirmDetachDocumentDialogHeight {
            get {
                return ((long)(this["ConfirmDetachDocumentDialogHeight"]));
            }
            set {
                this["ConfirmDetachDocumentDialogHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ConfirmDetachDocumentDialogWidth {
            get {
                return ((int)(this["ConfirmDetachDocumentDialogWidth"]));
            }
            set {
                this["ConfirmDetachDocumentDialogWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point ContinuationOfCounselingDialogLocation {
            get {
                return ((global::System.Drawing.Point)(this["ContinuationOfCounselingDialogLocation"]));
            }
            set {
                this["ContinuationOfCounselingDialogLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size ContinuationOfCounselingDialogSize {
            get {
                return ((global::System.Drawing.Size)(this["ContinuationOfCounselingDialogSize"]));
            }
            set {
                this["ContinuationOfCounselingDialogSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string ContinuationOfCounselingDialogSavedWindowState {
            get {
                return ((string)(this["ContinuationOfCounselingDialogSavedWindowState"]));
            }
            set {
                this["ContinuationOfCounselingDialogSavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ContinuationOfCounselingDialogHeight {
            get {
                return ((int)(this["ContinuationOfCounselingDialogHeight"]));
            }
            set {
                this["ContinuationOfCounselingDialogHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ContinuationOfCounselingDialogWidth {
            get {
                return ((int)(this["ContinuationOfCounselingDialogWidth"]));
            }
            set {
                this["ContinuationOfCounselingDialogWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point CounselingsForSoldierDialogLocation {
            get {
                return ((global::System.Drawing.Point)(this["CounselingsForSoldierDialogLocation"]));
            }
            set {
                this["CounselingsForSoldierDialogLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size CounselingsForSoldierDialogSize {
            get {
                return ((global::System.Drawing.Size)(this["CounselingsForSoldierDialogSize"]));
            }
            set {
                this["CounselingsForSoldierDialogSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string CounselingsForSoldierDialogSavedWindowState {
            get {
                return ((string)(this["CounselingsForSoldierDialogSavedWindowState"]));
            }
            set {
                this["CounselingsForSoldierDialogSavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CounselingsForSoldierDialogHeight {
            get {
                return ((int)(this["CounselingsForSoldierDialogHeight"]));
            }
            set {
                this["CounselingsForSoldierDialogHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CounselingsForSoldierDialogWidth {
            get {
                return ((int)(this["CounselingsForSoldierDialogWidth"]));
            }
            set {
                this["CounselingsForSoldierDialogWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point DocumentPropertiesDialogLocation {
            get {
                return ((global::System.Drawing.Point)(this["DocumentPropertiesDialogLocation"]));
            }
            set {
                this["DocumentPropertiesDialogLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size DocumentPropertiesDialogSize {
            get {
                return ((global::System.Drawing.Size)(this["DocumentPropertiesDialogSize"]));
            }
            set {
                this["DocumentPropertiesDialogSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string DocumentPropertiesDialogSavedWindowState {
            get {
                return ((string)(this["DocumentPropertiesDialogSavedWindowState"]));
            }
            set {
                this["DocumentPropertiesDialogSavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DocumentPropertiesDialogHeight {
            get {
                return ((int)(this["DocumentPropertiesDialogHeight"]));
            }
            set {
                this["DocumentPropertiesDialogHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DocumentPropertiesDialogWidth {
            get {
                return ((int)(this["DocumentPropertiesDialogWidth"]));
            }
            set {
                this["DocumentPropertiesDialogWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point DocumentsReportFiltersLocation {
            get {
                return ((global::System.Drawing.Point)(this["DocumentsReportFiltersLocation"]));
            }
            set {
                this["DocumentsReportFiltersLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size DocumentsReportFiltersSize {
            get {
                return ((global::System.Drawing.Size)(this["DocumentsReportFiltersSize"]));
            }
            set {
                this["DocumentsReportFiltersSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string DocumentsReportFiltersSavedWindowState {
            get {
                return ((string)(this["DocumentsReportFiltersSavedWindowState"]));
            }
            set {
                this["DocumentsReportFiltersSavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DocumentsReportFiltersHeight {
            get {
                return ((int)(this["DocumentsReportFiltersHeight"]));
            }
            set {
                this["DocumentsReportFiltersHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DocumentsReportFiltersWidth {
            get {
                return ((int)(this["DocumentsReportFiltersWidth"]));
            }
            set {
                this["DocumentsReportFiltersWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point EditNoteDialogLocation {
            get {
                return ((global::System.Drawing.Point)(this["EditNoteDialogLocation"]));
            }
            set {
                this["EditNoteDialogLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size EditNoteDialogSize {
            get {
                return ((global::System.Drawing.Size)(this["EditNoteDialogSize"]));
            }
            set {
                this["EditNoteDialogSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string EditNoteDialogSavedWindowState {
            get {
                return ((string)(this["EditNoteDialogSavedWindowState"]));
            }
            set {
                this["EditNoteDialogSavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EditNoteDialogHeight {
            get {
                return ((int)(this["EditNoteDialogHeight"]));
            }
            set {
                this["EditNoteDialogHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EditNoteDialogWidth {
            get {
                return ((int)(this["EditNoteDialogWidth"]));
            }
            set {
                this["EditNoteDialogWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point EditSoldierDialogLocation {
            get {
                return ((global::System.Drawing.Point)(this["EditSoldierDialogLocation"]));
            }
            set {
                this["EditSoldierDialogLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size EditSoldierDialogSize {
            get {
                return ((global::System.Drawing.Size)(this["EditSoldierDialogSize"]));
            }
            set {
                this["EditSoldierDialogSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string EditSoldierDialogSavedWindowState {
            get {
                return ((string)(this["EditSoldierDialogSavedWindowState"]));
            }
            set {
                this["EditSoldierDialogSavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EditSoldierDialogHeight {
            get {
                return ((int)(this["EditSoldierDialogHeight"]));
            }
            set {
                this["EditSoldierDialogHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EditSoldierDialogWidth {
            get {
                return ((int)(this["EditSoldierDialogWidth"]));
            }
            set {
                this["EditSoldierDialogWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point ExportSoldiersDialogLocation {
            get {
                return ((global::System.Drawing.Point)(this["ExportSoldiersDialogLocation"]));
            }
            set {
                this["ExportSoldiersDialogLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size ExportSoldiersDialogSize {
            get {
                return ((global::System.Drawing.Size)(this["ExportSoldiersDialogSize"]));
            }
            set {
                this["ExportSoldiersDialogSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string ExportSoldiersDialogSavedWindowState {
            get {
                return ((string)(this["ExportSoldiersDialogSavedWindowState"]));
            }
            set {
                this["ExportSoldiersDialogSavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ExportSoldiersDialogHeight {
            get {
                return ((int)(this["ExportSoldiersDialogHeight"]));
            }
            set {
                this["ExportSoldiersDialogHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ExportSoldiersDialogWidth {
            get {
                return ((int)(this["ExportSoldiersDialogWidth"]));
            }
            set {
                this["ExportSoldiersDialogWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LetterEditorLocation {
            get {
                return ((global::System.Drawing.Point)(this["LetterEditorLocation"]));
            }
            set {
                this["LetterEditorLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size LetterEditorSize {
            get {
                return ((global::System.Drawing.Size)(this["LetterEditorSize"]));
            }
            set {
                this["LetterEditorSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string LetterEditorSavedWindowState {
            get {
                return ((string)(this["LetterEditorSavedWindowState"]));
            }
            set {
                this["LetterEditorSavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LetterEditorHeight {
            get {
                return ((int)(this["LetterEditorHeight"]));
            }
            set {
                this["LetterEditorHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LetterEditorWidth {
            get {
                return ((int)(this["LetterEditorWidth"]));
            }
            set {
                this["LetterEditorWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point NewSoldierPage1DialogLocation {
            get {
                return ((global::System.Drawing.Point)(this["NewSoldierPage1DialogLocation"]));
            }
            set {
                this["NewSoldierPage1DialogLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size NewSoldierPage1DialogSize {
            get {
                return ((global::System.Drawing.Size)(this["NewSoldierPage1DialogSize"]));
            }
            set {
                this["NewSoldierPage1DialogSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string NewSoldierPage1DialogSavedWindowState {
            get {
                return ((string)(this["NewSoldierPage1DialogSavedWindowState"]));
            }
            set {
                this["NewSoldierPage1DialogSavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NewSoldierPage1DialogHeight {
            get {
                return ((int)(this["NewSoldierPage1DialogHeight"]));
            }
            set {
                this["NewSoldierPage1DialogHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NewSoldierPage1DialogWidth {
            get {
                return ((int)(this["NewSoldierPage1DialogWidth"]));
            }
            set {
                this["NewSoldierPage1DialogWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point NewSoldierPage2DialogLocation {
            get {
                return ((global::System.Drawing.Point)(this["NewSoldierPage2DialogLocation"]));
            }
            set {
                this["NewSoldierPage2DialogLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size NewSoldierPage2DialogSize {
            get {
                return ((global::System.Drawing.Size)(this["NewSoldierPage2DialogSize"]));
            }
            set {
                this["NewSoldierPage2DialogSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string NewSoldierPage2DialogSavedWindowState {
            get {
                return ((string)(this["NewSoldierPage2DialogSavedWindowState"]));
            }
            set {
                this["NewSoldierPage2DialogSavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NewSoldierPage2DialogHeight {
            get {
                return ((int)(this["NewSoldierPage2DialogHeight"]));
            }
            set {
                this["NewSoldierPage2DialogHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NewSoldierPage2DialogWidth {
            get {
                return ((int)(this["NewSoldierPage2DialogWidth"]));
            }
            set {
                this["NewSoldierPage2DialogWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PDFViewerFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["PDFViewerFormLocation"]));
            }
            set {
                this["PDFViewerFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size PDFViewerFormSize {
            get {
                return ((global::System.Drawing.Size)(this["PDFViewerFormSize"]));
            }
            set {
                this["PDFViewerFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string PDFViewerFormSavedWindowState {
            get {
                return ((string)(this["PDFViewerFormSavedWindowState"]));
            }
            set {
                this["PDFViewerFormSavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PDFViewerFormHeight {
            get {
                return ((int)(this["PDFViewerFormHeight"]));
            }
            set {
                this["PDFViewerFormHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PDFViewerFormWidth {
            get {
                return ((int)(this["PDFViewerFormWidth"]));
            }
            set {
                this["PDFViewerFormWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PregnancyElectionStatementEditorStepOneLocation {
            get {
                return ((global::System.Drawing.Point)(this["PregnancyElectionStatementEditorStepOneLocation"]));
            }
            set {
                this["PregnancyElectionStatementEditorStepOneLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size PregnancyElectionStatementEditorStepOneSize {
            get {
                return ((global::System.Drawing.Size)(this["PregnancyElectionStatementEditorStepOneSize"]));
            }
            set {
                this["PregnancyElectionStatementEditorStepOneSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string PregnancyElectionStatementEditorStepOneSavedWindowState {
            get {
                return ((string)(this["PregnancyElectionStatementEditorStepOneSavedWindowState"]));
            }
            set {
                this["PregnancyElectionStatementEditorStepOneSavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PregnancyElectionStatementEditorStepOneHeight {
            get {
                return ((int)(this["PregnancyElectionStatementEditorStepOneHeight"]));
            }
            set {
                this["PregnancyElectionStatementEditorStepOneHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PregnancyElectionStatementEditorStepOneWidth {
            get {
                return ((int)(this["PregnancyElectionStatementEditorStepOneWidth"]));
            }
            set {
                this["PregnancyElectionStatementEditorStepOneWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point CounselingsForSoldierLocation {
            get {
                return ((global::System.Drawing.Point)(this["CounselingsForSoldierLocation"]));
            }
            set {
                this["CounselingsForSoldierLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size CounselingsForSoldierSize {
            get {
                return ((global::System.Drawing.Size)(this["CounselingsForSoldierSize"]));
            }
            set {
                this["CounselingsForSoldierSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string CounselingsForSoldierSavedWindowState {
            get {
                return ((string)(this["CounselingsForSoldierSavedWindowState"]));
            }
            set {
                this["CounselingsForSoldierSavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CounselingsForSoldierHeight {
            get {
                return ((int)(this["CounselingsForSoldierHeight"]));
            }
            set {
                this["CounselingsForSoldierHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CounselingsForSoldierWidth {
            get {
                return ((int)(this["CounselingsForSoldierWidth"]));
            }
            set {
                this["CounselingsForSoldierWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PregnancyElectionStatementStepTwoLocation {
            get {
                return ((global::System.Drawing.Point)(this["PregnancyElectionStatementStepTwoLocation"]));
            }
            set {
                this["PregnancyElectionStatementStepTwoLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size PregnancyElectionStatementStepTwoSize {
            get {
                return ((global::System.Drawing.Size)(this["PregnancyElectionStatementStepTwoSize"]));
            }
            set {
                this["PregnancyElectionStatementStepTwoSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string PregnancyElectionStatementStepTwoSavedWindowState {
            get {
                return ((string)(this["PregnancyElectionStatementStepTwoSavedWindowState"]));
            }
            set {
                this["PregnancyElectionStatementStepTwoSavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PregnancyElectionStatementStepTwoHeight {
            get {
                return ((int)(this["PregnancyElectionStatementStepTwoHeight"]));
            }
            set {
                this["PregnancyElectionStatementStepTwoHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PregnancyElectionStatementStepTwoWidth {
            get {
                return ((int)(this["PregnancyElectionStatementStepTwoWidth"]));
            }
            set {
                this["PregnancyElectionStatementStepTwoWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PrintHTMLFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["PrintHTMLFormLocation"]));
            }
            set {
                this["PrintHTMLFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size PrintHTMLFormSize {
            get {
                return ((global::System.Drawing.Size)(this["PrintHTMLFormSize"]));
            }
            set {
                this["PrintHTMLFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string PrintHTMLFormSavedWindowState {
            get {
                return ((string)(this["PrintHTMLFormSavedWindowState"]));
            }
            set {
                this["PrintHTMLFormSavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PrintHTMLFormHeight {
            get {
                return ((int)(this["PrintHTMLFormHeight"]));
            }
            set {
                this["PrintHTMLFormHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PrintHTMLFormWidth {
            get {
                return ((int)(this["PrintHTMLFormWidth"]));
            }
            set {
                this["PrintHTMLFormWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point SoldierInfoDialogLocation {
            get {
                return ((global::System.Drawing.Point)(this["SoldierInfoDialogLocation"]));
            }
            set {
                this["SoldierInfoDialogLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size SoldierInfoDialogSize {
            get {
                return ((global::System.Drawing.Size)(this["SoldierInfoDialogSize"]));
            }
            set {
                this["SoldierInfoDialogSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string SoldierInfoDialogSavedWindowState {
            get {
                return ((string)(this["SoldierInfoDialogSavedWindowState"]));
            }
            set {
                this["SoldierInfoDialogSavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SoldierInfoDialogHeight {
            get {
                return ((int)(this["SoldierInfoDialogHeight"]));
            }
            set {
                this["SoldierInfoDialogHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SoldierInfoDialogWidth {
            get {
                return ((int)(this["SoldierInfoDialogWidth"]));
            }
            set {
                this["SoldierInfoDialogWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point UploadUserGeneratedCounselingFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["UploadUserGeneratedCounselingFormLocation"]));
            }
            set {
                this["UploadUserGeneratedCounselingFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size UploadUserGeneratedCounselingFormSize {
            get {
                return ((global::System.Drawing.Size)(this["UploadUserGeneratedCounselingFormSize"]));
            }
            set {
                this["UploadUserGeneratedCounselingFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string UploadUserGeneratedCounselingFormSavedWindowState {
            get {
                return ((string)(this["UploadUserGeneratedCounselingFormSavedWindowState"]));
            }
            set {
                this["UploadUserGeneratedCounselingFormSavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UploadUserGeneratedCounselingFormHeight {
            get {
                return ((int)(this["UploadUserGeneratedCounselingFormHeight"]));
            }
            set {
                this["UploadUserGeneratedCounselingFormHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UploadUserGeneratedCounselingFormWidth {
            get {
                return ((int)(this["UploadUserGeneratedCounselingFormWidth"]));
            }
            set {
                this["UploadUserGeneratedCounselingFormWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point XFDLEditorPage1Location {
            get {
                return ((global::System.Drawing.Point)(this["XFDLEditorPage1Location"]));
            }
            set {
                this["XFDLEditorPage1Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size XFDLEditorPage1Size {
            get {
                return ((global::System.Drawing.Size)(this["XFDLEditorPage1Size"]));
            }
            set {
                this["XFDLEditorPage1Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string XFDLEditorPage1SavedWindowState {
            get {
                return ((string)(this["XFDLEditorPage1SavedWindowState"]));
            }
            set {
                this["XFDLEditorPage1SavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XFDLEditorPage1Height {
            get {
                return ((int)(this["XFDLEditorPage1Height"]));
            }
            set {
                this["XFDLEditorPage1Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XFDLEditorPage1Width {
            get {
                return ((int)(this["XFDLEditorPage1Width"]));
            }
            set {
                this["XFDLEditorPage1Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point XFDLEditorPage2Location {
            get {
                return ((global::System.Drawing.Point)(this["XFDLEditorPage2Location"]));
            }
            set {
                this["XFDLEditorPage2Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size XFDLEditorPage2Size {
            get {
                return ((global::System.Drawing.Size)(this["XFDLEditorPage2Size"]));
            }
            set {
                this["XFDLEditorPage2Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string XFDLEditorPage2SavedWindowState {
            get {
                return ((string)(this["XFDLEditorPage2SavedWindowState"]));
            }
            set {
                this["XFDLEditorPage2SavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XFDLEditorPage2Height {
            get {
                return ((int)(this["XFDLEditorPage2Height"]));
            }
            set {
                this["XFDLEditorPage2Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XFDLEditorPage2Width {
            get {
                return ((int)(this["XFDLEditorPage2Width"]));
            }
            set {
                this["XFDLEditorPage2Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point ImportConflictDialogLocation {
            get {
                return ((global::System.Drawing.Point)(this["ImportConflictDialogLocation"]));
            }
            set {
                this["ImportConflictDialogLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size ImportConflictDialogSize {
            get {
                return ((global::System.Drawing.Size)(this["ImportConflictDialogSize"]));
            }
            set {
                this["ImportConflictDialogSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string ImportConflictDialogSavedWindowState {
            get {
                return ((string)(this["ImportConflictDialogSavedWindowState"]));
            }
            set {
                this["ImportConflictDialogSavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ImportConflictDialogHeight {
            get {
                return ((int)(this["ImportConflictDialogHeight"]));
            }
            set {
                this["ImportConflictDialogHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ImportConflictDialogWidth {
            get {
                return ((int)(this["ImportConflictDialogWidth"]));
            }
            set {
                this["ImportConflictDialogWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LegalNoticeLocation {
            get {
                return ((global::System.Drawing.Point)(this["LegalNoticeLocation"]));
            }
            set {
                this["LegalNoticeLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size LegalNoticeSize {
            get {
                return ((global::System.Drawing.Size)(this["LegalNoticeSize"]));
            }
            set {
                this["LegalNoticeSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string LegalNoticeSavedWindowState {
            get {
                return ((string)(this["LegalNoticeSavedWindowState"]));
            }
            set {
                this["LegalNoticeSavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LegalNoticeHeight {
            get {
                return ((int)(this["LegalNoticeHeight"]));
            }
            set {
                this["LegalNoticeHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LegalNoticeWidth {
            get {
                return ((int)(this["LegalNoticeWidth"]));
            }
            set {
                this["LegalNoticeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point NewDocumentPresetDialogLocation {
            get {
                return ((global::System.Drawing.Point)(this["NewDocumentPresetDialogLocation"]));
            }
            set {
                this["NewDocumentPresetDialogLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size NewDocumentPresetDialogSize {
            get {
                return ((global::System.Drawing.Size)(this["NewDocumentPresetDialogSize"]));
            }
            set {
                this["NewDocumentPresetDialogSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string NewDocumentPresetDialogSavedWindowState {
            get {
                return ((string)(this["NewDocumentPresetDialogSavedWindowState"]));
            }
            set {
                this["NewDocumentPresetDialogSavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NewDocumentPresetDialogHeight {
            get {
                return ((int)(this["NewDocumentPresetDialogHeight"]));
            }
            set {
                this["NewDocumentPresetDialogHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NewDocumentPresetDialogWidth {
            get {
                return ((int)(this["NewDocumentPresetDialogWidth"]));
            }
            set {
                this["NewDocumentPresetDialogWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point OptionsDialogLocation {
            get {
                return ((global::System.Drawing.Point)(this["OptionsDialogLocation"]));
            }
            set {
                this["OptionsDialogLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size OptionsDialogSize {
            get {
                return ((global::System.Drawing.Size)(this["OptionsDialogSize"]));
            }
            set {
                this["OptionsDialogSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string OptionsDialogSavedWindowState {
            get {
                return ((string)(this["OptionsDialogSavedWindowState"]));
            }
            set {
                this["OptionsDialogSavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OptionsDialogHeight {
            get {
                return ((int)(this["OptionsDialogHeight"]));
            }
            set {
                this["OptionsDialogHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OptionsDialogWidth {
            get {
                return ((int)(this["OptionsDialogWidth"]));
            }
            set {
                this["OptionsDialogWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PromptToCompleteCounselingPackageDialogLocation {
            get {
                return ((global::System.Drawing.Point)(this["PromptToCompleteCounselingPackageDialogLocation"]));
            }
            set {
                this["PromptToCompleteCounselingPackageDialogLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size PromptToCompleteCounselingPackageDialogSize {
            get {
                return ((global::System.Drawing.Size)(this["PromptToCompleteCounselingPackageDialogSize"]));
            }
            set {
                this["PromptToCompleteCounselingPackageDialogSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string PromptToCompleteCounselingPackageDialogSavedWindowState {
            get {
                return ((string)(this["PromptToCompleteCounselingPackageDialogSavedWindowState"]));
            }
            set {
                this["PromptToCompleteCounselingPackageDialogSavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PromptToCompleteCounselingPackageDialogHeight {
            get {
                return ((int)(this["PromptToCompleteCounselingPackageDialogHeight"]));
            }
            set {
                this["PromptToCompleteCounselingPackageDialogHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PromptToCompleteCounselingPackageDialogWidth {
            get {
                return ((int)(this["PromptToCompleteCounselingPackageDialogWidth"]));
            }
            set {
                this["PromptToCompleteCounselingPackageDialogWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PromptToSubmitCrashReportLocation {
            get {
                return ((global::System.Drawing.Point)(this["PromptToSubmitCrashReportLocation"]));
            }
            set {
                this["PromptToSubmitCrashReportLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size PromptToSubmitCrashReportSize {
            get {
                return ((global::System.Drawing.Size)(this["PromptToSubmitCrashReportSize"]));
            }
            set {
                this["PromptToSubmitCrashReportSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string PromptToSubmitCrashReportSavedWindowState {
            get {
                return ((string)(this["PromptToSubmitCrashReportSavedWindowState"]));
            }
            set {
                this["PromptToSubmitCrashReportSavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PromptToSubmitCrashReportHeight {
            get {
                return ((int)(this["PromptToSubmitCrashReportHeight"]));
            }
            set {
                this["PromptToSubmitCrashReportHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PromptToSubmitCrashReportWidth {
            get {
                return ((int)(this["PromptToSubmitCrashReportWidth"]));
            }
            set {
                this["PromptToSubmitCrashReportWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point RecycleBinDialogLocation {
            get {
                return ((global::System.Drawing.Point)(this["RecycleBinDialogLocation"]));
            }
            set {
                this["RecycleBinDialogLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size RecycleBinDialogSize {
            get {
                return ((global::System.Drawing.Size)(this["RecycleBinDialogSize"]));
            }
            set {
                this["RecycleBinDialogSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string RecycleBinDialogSavedWindowState {
            get {
                return ((string)(this["RecycleBinDialogSavedWindowState"]));
            }
            set {
                this["RecycleBinDialogSavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RecycleBinDialogHeight {
            get {
                return ((int)(this["RecycleBinDialogHeight"]));
            }
            set {
                this["RecycleBinDialogHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RecycleBinDialogWidth {
            get {
                return ((int)(this["RecycleBinDialogWidth"]));
            }
            set {
                this["RecycleBinDialogWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point SelectNewParentDocumentDialogLocation {
            get {
                return ((global::System.Drawing.Point)(this["SelectNewParentDocumentDialogLocation"]));
            }
            set {
                this["SelectNewParentDocumentDialogLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size SelectNewParentDocumentDialogSize {
            get {
                return ((global::System.Drawing.Size)(this["SelectNewParentDocumentDialogSize"]));
            }
            set {
                this["SelectNewParentDocumentDialogSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string SelectNewParentDocumentDialogSavedWindowState {
            get {
                return ((string)(this["SelectNewParentDocumentDialogSavedWindowState"]));
            }
            set {
                this["SelectNewParentDocumentDialogSavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectNewParentDocumentDialogHeight {
            get {
                return ((int)(this["SelectNewParentDocumentDialogHeight"]));
            }
            set {
                this["SelectNewParentDocumentDialogHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectNewParentDocumentDialogWidth {
            get {
                return ((int)(this["SelectNewParentDocumentDialogWidth"]));
            }
            set {
                this["SelectNewParentDocumentDialogWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point SelectSoldierDialogLocation {
            get {
                return ((global::System.Drawing.Point)(this["SelectSoldierDialogLocation"]));
            }
            set {
                this["SelectSoldierDialogLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size SelectSoldierDialogSize {
            get {
                return ((global::System.Drawing.Size)(this["SelectSoldierDialogSize"]));
            }
            set {
                this["SelectSoldierDialogSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string SelectSoldierDialogSavedWindowState {
            get {
                return ((string)(this["SelectSoldierDialogSavedWindowState"]));
            }
            set {
                this["SelectSoldierDialogSavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectSoldierDialogHeight {
            get {
                return ((int)(this["SelectSoldierDialogHeight"]));
            }
            set {
                this["SelectSoldierDialogHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectSoldierDialogWidth {
            get {
                return ((int)(this["SelectSoldierDialogWidth"]));
            }
            set {
                this["SelectSoldierDialogWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point SelectTemplateValuesDialogLocation {
            get {
                return ((global::System.Drawing.Point)(this["SelectTemplateValuesDialogLocation"]));
            }
            set {
                this["SelectTemplateValuesDialogLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size SelectTemplateValuesDialogSize {
            get {
                return ((global::System.Drawing.Size)(this["SelectTemplateValuesDialogSize"]));
            }
            set {
                this["SelectTemplateValuesDialogSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string SelectTemplateValuesDialogSavedWindowState {
            get {
                return ((string)(this["SelectTemplateValuesDialogSavedWindowState"]));
            }
            set {
                this["SelectTemplateValuesDialogSavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectTemplateValuesDialogHeight {
            get {
                return ((int)(this["SelectTemplateValuesDialogHeight"]));
            }
            set {
                this["SelectTemplateValuesDialogHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectTemplateValuesDialogWidth {
            get {
                return ((int)(this["SelectTemplateValuesDialogWidth"]));
            }
            set {
                this["SelectTemplateValuesDialogWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point SoldierReportFiltersDialogLocation {
            get {
                return ((global::System.Drawing.Point)(this["SoldierReportFiltersDialogLocation"]));
            }
            set {
                this["SoldierReportFiltersDialogLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size SoldierReportFiltersDialogSize {
            get {
                return ((global::System.Drawing.Size)(this["SoldierReportFiltersDialogSize"]));
            }
            set {
                this["SoldierReportFiltersDialogSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string SoldierReportFiltersDialogSavedWindowState {
            get {
                return ((string)(this["SoldierReportFiltersDialogSavedWindowState"]));
            }
            set {
                this["SoldierReportFiltersDialogSavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SoldierReportFiltersDialogHeight {
            get {
                return ((int)(this["SoldierReportFiltersDialogHeight"]));
            }
            set {
                this["SoldierReportFiltersDialogHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SoldierReportFiltersDialogWidth {
            get {
                return ((int)(this["SoldierReportFiltersDialogWidth"]));
            }
            set {
                this["SoldierReportFiltersDialogWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point XFDLExportOverflowWarningDialogLocation {
            get {
                return ((global::System.Drawing.Point)(this["XFDLExportOverflowWarningDialogLocation"]));
            }
            set {
                this["XFDLExportOverflowWarningDialogLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size XFDLExportOverflowWarningDialogSize {
            get {
                return ((global::System.Drawing.Size)(this["XFDLExportOverflowWarningDialogSize"]));
            }
            set {
                this["XFDLExportOverflowWarningDialogSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string XFDLExportOverflowWarningDialogSavedWindowState {
            get {
                return ((string)(this["XFDLExportOverflowWarningDialogSavedWindowState"]));
            }
            set {
                this["XFDLExportOverflowWarningDialogSavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XFDLExportOverflowWarningDialogHeight {
            get {
                return ((int)(this["XFDLExportOverflowWarningDialogHeight"]));
            }
            set {
                this["XFDLExportOverflowWarningDialogHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XFDLExportOverflowWarningDialogWidth {
            get {
                return ((int)(this["XFDLExportOverflowWarningDialogWidth"]));
            }
            set {
                this["XFDLExportOverflowWarningDialogWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point GenericMemoEditorStepTwoLocation {
            get {
                return ((global::System.Drawing.Point)(this["GenericMemoEditorStepTwoLocation"]));
            }
            set {
                this["GenericMemoEditorStepTwoLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size GenericMemoEditorStepTwoSize {
            get {
                return ((global::System.Drawing.Size)(this["GenericMemoEditorStepTwoSize"]));
            }
            set {
                this["GenericMemoEditorStepTwoSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string GenericMemoEditorStepTwoSavedWindowState {
            get {
                return ((string)(this["GenericMemoEditorStepTwoSavedWindowState"]));
            }
            set {
                this["GenericMemoEditorStepTwoSavedWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GenericMemoEditorStepTwoHeight {
            get {
                return ((int)(this["GenericMemoEditorStepTwoHeight"]));
            }
            set {
                this["GenericMemoEditorStepTwoHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GenericMemoEditorStepTwoWidth {
            get {
                return ((int)(this["GenericMemoEditorStepTwoWidth"]));
            }
            set {
                this["GenericMemoEditorStepTwoWidth"] = value;
            }
        }
    }
}
